lib/elen_web/router.ex
defmodule ElenWeb.Router do
  use ElenWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated, error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug ElenWeb.ApiAuthPlug, otp_app: :elen
  end

  pipeline :api_protected do
    plug Pow.Plug.RequireAuthenticated, error_handler: ElenWeb.ApiAuthErrorHandler
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
  end

  scope "/", ElenWeb do
    pipe_through :browser

    get "/", PageController, :index
    # resources "/photos", PhotoController
    get "/found/:code", FoundController, :show
  end

  scope "/", ElenWeb do
    pipe_through [:browser, :protected]

    resources "/conversations", ConversationController
    resources "/items", ItemController
    resources "/users", UserController, except: [:create]
    live "/conversations/:conversation_id/users/:user_id", ConversationLive, as: :conversation
  end

  scope "/api", ElenWeb do
    pipe_through :api
    resources "/registration", Api.RegistrationController, singleton: true, only: [:create]
    resources "/session", Api.SessionController, singleton: true, only: [:create, :delete]
    post "/session/renew", Api.SessionController, :renew
    resources "/users", Api.UserController, except: [:create] # move to protected

    get "/found/:code", Api.FoundController, :show
  end

  scope "/api", ElenWeb do
    pipe_through [:api, :api_protected]
    resources "/items", Api.ItemController
  end

end

lib/elen_web/controllers/api/user_controller.ex
defmodule ElenWeb.Api.UserController do
  use ElenWeb, :controller

  alias Elen.Auth
  alias Elen.Auth.User

  def index(conn, _params) do
    users = Auth.list_auth_users()
    render(conn, "index.json", users: users)
  end

  def show(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    render(conn, "show.json", user: user)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)

    with {:ok, %User{} = user} <- Auth.update_user(user, user_params) do
      render(conn, "show.json", user: user)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Auth.get_user!(id)

    with {:ok, %User{}} <- Auth.delete_user(user) do
      send_resp(conn, :no_content, "")
    end
  end

end

lib/elen_web/controllers/user_controller.ex
defmodule ElenWeb.UserController do
  use ElenWeb, :controller

  alias Elen.Auth
  alias Elen.Auth.User

  def index(conn, _params) do
    users = Auth.list_auth_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Auth.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def show(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    changeset = Auth.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)

    case Auth.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    {:ok, _user} = Auth.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

end

lib/elen_web/views/user_view.ex
defmodule ElenWeb.UserView do
  use ElenWeb, :view
end

lib/elen_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/elen_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :nickname %>
  <%= text_input f, :nickname %>
  <%= error_tag f, :nickame %>

  <%= label f, :firstname %>
  <%= text_input f, :firstname %>
  <%= error_tag f, :firstname %>

  <%= label f, :lastname %>
  <%= text_input f, :lastname %>
  <%= error_tag f, :lastname %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/elen_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.nickname %></td>
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/elen_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.item_path(@conn, :index) %></span>

lib/elen_web/templates/user/show.html.eex
<h1>Show User</h1>

<p><strong>Nickname:</strong> <%= @user.nickname %></p>
<p><strong>Firstname:</strong> <%= @user.firstname %></p>
<p><strong>Lastname:</strong> <%= @user.lastname %></p>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>